# Exercise 1: Data cleaning

Before doing actual data analysis, we usually first need to clean the data.
This might involve steps such as dealing with missing values and encoding categorical variables as integers.
In this exercise, you will perform such steps based on the Titanic passenger data.

1. Load the Titanic data set in `titanic.csv` located in the `data/` folder.
2. Report the number of observations with missing `Age`, for example using
   [`isna()`](https://pandas.pydata.org/docs/reference/api/pandas.isna.html).
3. Compute the average age in the data set. Use the following approaches and compare your results:
    1.  Use pandas's
        [`mean()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.mean.html)
        method.

        *Hint:* Select the `Age` column first, then call its `mean()` method.

    2.  Convert the `Age` column to a NumPy array using
        [`to_numpy()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html).
        Experiment with NumPy's
        [`np.mean()`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)
        and
        [`np.nanmean()`](https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html)
        to see if you obtain the same results.
4. Replace all missing ages with the mean age you computed above, rounded to the nearest integer.
   You can either identify the missing values using a boolean mask and assign the mean
   age to those entries, or use
   [`fillna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html).

   Convert this updated `Age` column to integer type using
   [`astype()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.astype.html).

   *Hint:* Use `astype(int)`.

5. Generate a new column `Female` which takes on the value one if `Sex` is equal
   to `"female"` and zero if `Sex` is equal to `"male"`.
   This is called an _indicator_ or _dummy_ variable, and is useful for numerical
   analysis or regression.
   Delete the original column `Sex`.

   *Hint:* Create a new column using `df['new_column'] = values`, replacing
   `new_column` with the desired column name and `values` with the data to store.

6. Save your cleaned data set as `titanic-clean.csv` using
   [`to_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html)
   with `,` as the field separator.
   Tell `to_csv()` to *not* write the `DataFrame` index to the CSV file as it's not needed in this example.

## Solution
#### Part 1

In [314]:
import pandas as pd


file = "../../data/titanic.csv"

df = pd.read_csv(file)

#### Part 2

In [315]:
no_age = df["Age"].isna().sum()
print(f"{no_age} observations are missing age")

177 observations are missing age

#### Part 3

In [316]:
avg_age = df["Age"].mean()
print(f"The average age is {avg_age:.0f}")

The average age is 30

#### Part 4

In [317]:
df["Age"] = df["Age"].fillna(avg_age)
df.info(show_counts=True) 
#Ser at det er nå 891 "non-null" i dataframen

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   Ticket       891 non-null    str
 7   Fare         891 non-null    float64
 8   Cabin        204 non-null    str
 9   Embarked     889 non-null    str
dtypes: float64(2), int64(3), str(5)
memory usage: 69.7 KB

#### Part 5

In [318]:
df["Female"] = (df["Sex"]=="female").astype(int)
del (df["Sex"])

#### Part 6

In [319]:
df.to_csv("../../data/Titanic_clean.csv", sep=',', index=False)

***
# Exercise 2: Selecting subsets of data

In this exercise, you are asked to select subsets of macroeconomic data for the United States based on some criteria.

1.  Load the annual data from FRED which are located in `FRED_annual.xlsx`
    in the `data/FRED` folder.

    Print the list of columns and the number of non-missing observations.

    Since we are dealing with time series data, set the column `Year` as the `DataFrame`
    index.

2.  Print all observations for the 1960s decade using at least two different methods.

3.  Using the data in the column `GDP`, compute the annual GDP growth in percent
    and store it in the column `GDP_growth`. Select the years in which

    1.  GDP growth was above 5%.
    2.  GDP growth was negative, but inflation was still above 5% (such episodes are called "stagflation" since usually negative GDP growth is associated with low inflation).

        Use at least two methods for the stagflation selection.

    *Hint:* You can compute changes relative to the previous observation using the
    [`pct_change()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.pct_change.html)
    method.

## Solution
#### Part 1

In [320]:
file = "../../data/FRED/FRED_annual.xlsx"
df = pd.read_excel(file)
df = df.set_index("Year")
df.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 1954 to 2025
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   GDP        72 non-null     float64
 1   CPI        72 non-null     float64
 2   UNRATE     72 non-null     float64
 3   FEDFUNDS   72 non-null     float64
 4   INFLATION  71 non-null     float64
dtypes: float64(5)
memory usage: 2.9 KB

#### Part 2

In [321]:
#method 1
df.loc[1960:1969]

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION
Year
1960  3500.3  29.6     5.5       3.2   1.369863
1961  3590.1  29.9     6.7       2.0   1.013514
1962  3810.1  30.3     5.6       2.7   1.337793
1963  3976.1  30.6     5.6       3.2   0.990099
1964  4205.3  31.0     5.2       3.5   1.307190
1965  4478.6  31.5     4.5       4.1   1.612903
1966  4773.9  32.5     3.8       5.1   3.174603
1967  4904.9  33.4     3.8       4.2   2.769231
1968  5145.9  34.8     3.6       5.7   4.191617
1969  5306.6  36.7     3.5       8.2   5.459770

In [322]:
#Method 2
df.query("1960 <= Year < 1970")

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION
Year
1960  3500.3  29.6     5.5       3.2   1.369863
1961  3590.1  29.9     6.7       2.0   1.013514
1962  3810.1  30.3     5.6       2.7   1.337793
1963  3976.1  30.6     5.6       3.2   0.990099
1964  4205.3  31.0     5.2       3.5   1.307190
1965  4478.6  31.5     4.5       4.1   1.612903
1966  4773.9  32.5     3.8       5.1   3.174603
1967  4904.9  33.4     3.8       4.2   2.769231
1968  5145.9  34.8     3.6       5.7   4.191617
1969  5306.6  36.7     3.5       8.2   5.459770

#### Part 3

In [323]:
df["GDP_growth"] = df["GDP"].pct_change()*100

In [324]:
df.query("GDP_growth > 5")

          GDP    CPI  UNRATE  FEDFUNDS  INFLATION  GDP_growth
Year
1955   3083.0   26.8     4.4       1.8  -0.371747    7.134170
1959   3412.4   29.2     5.4       3.3   1.038062    6.931562
1962   3810.1   30.3     5.6       2.7   1.337793    6.127963
1964   4205.3   31.0     5.2       3.5   1.307190    5.764443
1965   4478.6   31.5     4.5       4.1   1.612903    6.498942
1966   4773.9   32.5     3.8       5.1   3.174603    6.593578
1972   5780.0   41.8     5.6       4.4   3.209877    5.255490
1973   6106.4   44.4     4.9       8.7   6.220096    5.647059
1976   6387.4   56.9     7.7       5.0   5.762082    5.386989
1978   7052.7   65.2     6.1       7.9   7.590759    5.535105
1984   8195.3  103.9     7.5      10.2   4.317269    7.236042
2021  21532.4  271.0     5.4       0.1   4.673619    6.151988

In [325]:
df.query("GDP_growth < 0 & INFLATION > 5")

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION  GDP_growth
Year
1974  6073.4  49.3     5.6      10.5  11.036036   -0.540417
1975  6060.9  53.8     8.5       5.8   9.127789   -0.205816
1980  7257.3  82.4     7.2      13.4  13.498623   -0.257009
1982  7307.3  96.5     9.7      12.3   6.160616   -1.803400

***
# Exercise 3: Labor market statistics for the US

In this exercise, you are asked to compute some descriptive statistics for the
unemployment rate and the labor force participation rate for the United States.
The latter is the percentage of the civilian noninstitutional population aged 16
and older who are in the labor force (employed or unemployed). Both rates are
expressed as percentages.

1.  Load the monthly time series from FRED which are located in `FRED_monthly.csv`
    in the `data/FRED` folder.

    *Hint:* Use `pd.read_csv(..., parse_dates=['DATE'])` to automatically
    parse strings stored in the `DATE` column as dates.

    Since we are dealing with time series data, set the column `DATE` as the
    `DataFrame` index. Then print the list of columns and the number of non-missing
    observations.

2.  For the columns `UNRATE` (unemployment rate) and `LFPART` (labor force
    participation rate), compute and report
    the mean, minimum, and maximum values for the whole sample. Round your results
    to one decimal place.

    *Hint:* You can use the `DataFrame` methods
    [`mean()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html),
    [`min()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.min.html), and
    [`max()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.max.html)
    to compute the desired statistics.

    *Hint:* You can use the `DataFrame` method
    [`round()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.round.html)
    to round the results to one decimal place.

3.  You are interested in how the average unemployment rate evolved over the last
    few decades.

    -   Add a new column `Decade` to the `DataFrame` which contains the
        starting year for each decade (e.g., this value should be 1950
        for the years 1950-1959, and so on).

        *Hint:* The decade can be computed from the column `Year` using
        truncated integer division:
        ```python
        df['Year'] // 10 * 10
        ```

    -   Write a loop to compute and report the average unemployment rate
        (column `UNRATE`) for each decade.

        Include only the decades from 1950 to 2010 for which you have all
        observations.

## Solution
##### Part 1

In [326]:
file = "../../data/FRED/FRED_monthly.csv"
df = pd.read_csv(file, parse_dates=["DATE"])

#### Part 2

In [327]:
df[["UNRATE", "LFPART"]].describe().loc[["mean", "min", "max"]].round(1)

      UNRATE  LFPART
mean     5.7    62.8
min      2.5    58.1
max     14.8    67.3

#### Part 3

In [328]:
import numpy as np


df["Decade"]=df["Year"]//10*10
df = df.query("1940 < Decade <=2010")

decades = np.linspace(1950, 2010, 7)

for decade in decades:
    mean = df.loc[df["Decade"] == decade, "UNRATE"].mean()
    print(f"The average unemploymentrate in {decade:.0f} was {mean:.2f}")

The average unemploymentrate in 1950 was 4.51
The average unemploymentrate in 1960 was 4.78
The average unemploymentrate in 1970 was 6.22
The average unemploymentrate in 1980 was 7.27
The average unemploymentrate in 1990 was 5.76
The average unemploymentrate in 2000 was 5.54
The average unemploymentrate in 2010 was 6.22

***
# Exercise 4: Daily stock-market returns

In this exercise, you will compute daily returns for the S&P 500 index and count
trading days with losses or large gains. The column `SP500` contains the index
values.

1.  Load `SP500.csv` from the `data/stockmarket` folder, parse `Date` as dates, and
    set it as the `DataFrame` index. Restrict the data to observations after
    January 1, 2020.

    *Hint:* Use `pd.read_csv(..., parse_dates=['Date'])` to automatically parse the
    strings in the `Date` column as dates.

2.  Compute daily returns in percent using
    [`pct_change()`](
    https://pandas.pydata.org/docs/reference/api/pandas.Series.pct_change.html
    )
    and store them in a new column `Return`. Explain why the first return is
    missing.

    *Hint:* Multiply the result of `pct_change()` by 100 to express returns in
    percent.

3.  Report the number and percentage of trading days with losses, i.e., negative
    returns. Exclude days with missing returns from the denominator.

    *Hint:* Summing a Boolean `Series` counts the number of `True` values. Use
    [`count()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.count.html)
    to count nonmissing observations.

4.  Report the number and percentage of trading days with gains of more than 5%.
5.  Report the number and percentage of days with negative returns on both the
    current and the previous trading day. A run of three loss days contributes
    two qualifying days. For the percentage, include only days with both returns
    observed.

    *Hint:* Use
    [`shift()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.shift.html)
    to obtain the previous trading day's return, and combine the two conditions
    using `&`.

## Solution
#### Part 1

In [329]:
file = "../../data/stockmarket/SP500.csv"
df = pd.read_csv(file, parse_dates=["Date"])
df = df.set_index("Date")
df = df.loc[df.index >= '2020-01-01']
df.head()

             SP500
Date
2020-01-02  3257.9
2020-01-03  3234.9
2020-01-06  3246.3
2020-01-07  3237.2
2020-01-08  3253.1

#### Part 2

In [330]:
df["Return"] = df["SP500"].pct_change()*100
df.head()
df.info(show_counts=True)

<class 'pandas.DataFrame'>
DatetimeIndex: 1507 entries, 2020-01-02 to 2025-12-30
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SP500   1507 non-null   float64
 1   Return  1506 non-null   float64
dtypes: float64(2)
memory usage: 35.3 KB

#### Part 3

In [334]:
days_down = df["Return"] < 0

ndays = df["Return"].count()
#Value counts shows that the market was up 10762 days and down 8358 days.
days_down.value_counts()

print(f"The market went down {days_down.sum()} days.")
print(f"The market went down {(days_down.sum())/ndays:.2%} of the time.")

The market went down 685 days.
The market went down 45.48% of the time.

#### Part 4

In [336]:
days5 = df["Return"] > 5
print(f"The market went up more then 5% {days5.sum()} days.")
print(f"The market went up more then 5% {days5.sum()/ndays:.2%} of days.")

The market went up more then 5% 7 days.
The market went up more then 5% 0.46% of days.

#### Part 5

In [338]:
neg2 = (df["Return"] < 0) & (df["Return"].shift() < 0)
print(f"The marked had consecutive negative days {neg2.sum()} times.")
print(f"The marked had consecutive negative days {neg2.sum()/ndays:.2%} of days.")

The marked had consecutive negative days 296 times.
The marked had consecutive negative days 19.65% of days.

***
# Exercise 5: Working with string data (advanced)

Most of the data we deal with contain strings, i.e., text data (names, addresses, etc.). Often, such data is not in the format needed for analysis, and we have to perform additional string manipulation to extract the exact data we need. This can be achieved using the pandas
[string methods](https://pandas.pydata.org/docs/user_guide/text.html#string-methods).

To illustrate, we use the Titanic data set for this exercise.

1.  Load the Titanic data and restrict the sample to men. (This simplifies the task. Some
    married women's entries contain both their husband's name and their maiden name.)
2.  Print the first five observations of the `Name` column. As you can see, the data is stored in the format _"Last name, Title First name"_ where the title is something like Mr., Rev., etc.
3.  Split the `Name` column by `,` to extract the last name and the remainder as separate columns. You can achieve this using the
   [`partition()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.partition.html)
   string method.
4. Split the remainder (containing the title and first name) using the space
   character `" "` as separator to obtain individual columns for the title and
   the first name.

   *Hint:* The remainder starts with a space after the comma. Use `.str.strip()`
   to remove leading and trailing whitespace before splitting it.

5. Store the three data series in the original `DataFrame` (using the column names `FirstName`, `LastName`, and `Title`) and delete the `Name` column, which is no longer needed.
6. Finally, extract the ship deck from the values in `Cabin`. The ship deck is the first character in the string stored in `Cabin` (A, B, C, ...). You extract the first character using the
   [`get()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.get.html)
   string method. Store the result in the column `Deck`.

*Hint*: pandas's string methods can be accessed using the `.str` attribute. For example,
to partition values in the column `Name`, you need to use
```python
df['Name'].str.partition()
```

## Solution
#### Part 1

In [57]:
import pandas as pd 


file = "../../data/titanic.csv"
df = pd.read_csv(file)

df_male = df.query("Sex == 'male'")
df_male.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,349909,21.0750,NaN,S

#### Part 2

In [58]:
df_male["Name"].head(5)

0          Braund, Mr. Owen Harris
4         Allen, Mr. William Henry
5                 Moran, Mr. James
6          McCarthy, Mr. Timothy J
7    Palsson, Master Gosta Leonard
Name: Name, dtype: str

#### Part 3

In [59]:
df_names = df_male["Name"].str.partition(",")
df_names.head(5)

          0  1                      2
0    Braund  ,        Mr. Owen Harris
4     Allen  ,      Mr. William Henry
5     Moran  ,              Mr. James
6  McCarthy  ,          Mr. Timothy J
7   Palsson  ,   Master Gosta Leonard

In [60]:
#need to use.str.strip to remove anything but the last names
last_name = df_names[0].str.strip()
last_name.head(5)

0      Braund
4       Allen
5       Moran
6    McCarthy
7     Palsson
Name: 0, dtype: str

#### Part 4

In [61]:
#First i use string strip to pull only the title and name from the old colum 2.
#Then I use partition on this to split the name and title
name_title = df_names[2].str.strip().str.partition()
name_title.head(5)

        0  1              2
0     Mr.       Owen Harris
4     Mr.     William Henry
5     Mr.             James
6     Mr.         Timothy J
7  Master     Gosta Leonard

In [62]:
title = name_title[0].str.strip()
first_name = name_title[2].str.strip()

#### Part 5

In [63]:
#Adding the new columns
df_male["Title"] = title
df_male["FirstName"] = first_name
df_male["LastName"] = last_name

#Deleting the old name column
del df_male["Name"]

df_male.head(5)

,PassengerId,Survived,Pclass,Sex,Age,Ticket,Fare,Cabin,Embarked,Title,FirstName,LastName
0,1,0,3,male,22.0,A/5 21171,7.2500,NaN,S,Mr.,Owen Harris,Braund
4,5,0,3,male,35.0,373450,8.0500,NaN,S,Mr.,William Henry,Allen
5,6,0,3,male,NaN,330877,8.4583,NaN,Q,Mr.,James,Moran
6,7,0,1,male,54.0,17463,51.8625,E46,S,Mr.,Timothy J,McCarthy
7,8,0,3,male,2.0,349909,21.0750,NaN,S,Master,Gosta Leonard,Palsson